---
- name: update my_groceries
  hosts: my_groceries
  remote_user: root
  tasks:
    # Code
    - name: Pull the code
      ansible.builtin.git:
        repo: "{{project_git_url}}"
        dest: "{{project_dir}}"
    - name: Install monorepo dependencies
      community.general.npm:
        path: "{{project_dir}}"
    - name: Copy app .env
      ansible.builtin.template:
        src: templates/app.env.j2
        dest: "{{project_dir}}/app/.env"
    - name: Copy service .env
      ansible.builtin.template:
        src: templates/service.env.j2
        dest: "{{project_dir}}/service/.env"
    - name: Build app
      ansible.builtin.shell:
        cmd: "npm run build"
        chdir: "{{project_dir}}/app"
    # Database migrations
    - name: Migrate persistence
      ansible.builtin.shell:
        cmd: npm run migrate:latest
        chdir: "{{project_dir}}/persistence"
    # Restart everything
    - name: Restart service
      ansible.builtin.shell:
        cmd: pm2 restart service
    - name: Build landing
      ansible.builtin.shell:
        cmd: npm run build
        chdir: "{{project_dir}}/landing"
    - name: Restart landing
      ansible.builtin.shell:
        cmd: pm2 restart landing
    - name: pm2 startup
      ansible.builtin.shell:
        cmd: pm2 startup
    - name: pm2 save
      ansible.builtin.shell:
        cmd: pm2 save
    # Caddy
    - name: Restart caddy
      ansible.builtin.systemd:
        name: caddy
        state: restarted
